/**
 * @description Public class to use query profile and contain profile specific contants
 *
 * @author Accenture
 *
 * @date 2019
 */
public inherited sharing class AW_DAL_Profile
{
	public static final String PROFILE_ADVISER = 'Liberty Adviser';
	public static final String PROFILE_CLIENT = 'Liberty Client Community User';
	public static final String PROFILE_LIBERTY_ADMIN = 'Liberty Administrator';
	public static final String PROFILE_LIBERTY_LEAD_MANAGER = 'Liberty Lead Manager';
	public static final String PROFILE_LIBERTY_SERVICE_ACCOUNT = 'Liberty Service Account';
	public static final String PROFILE_LIBERTY_SUPPORT = 'Liberty Support';
	public static final String PROFILE_PERSONAL_ASSISTANT = 'Liberty Adviser Personal Assistant';
	public static final String PROFILE_SALES_LEADER = 'Liberty Sales Leader';
}