/**
 * @description Test Class for AW_AUTH_DiscoveryCommunity
 *
 * @author Accenture
 *
 * @date 2019
 */
@IsTest(SeeAllData=false IsParallel=true)
private class AW_TEST_AUTH_DiscoveryCommunity
{
	/**
	 * @description Method to run code on AW_AUTH_DiscoveryCommunity because we unable to delete class
	 */
	@IsTest
	private static void runCode()
	{
		new AW_AUTH_DiscoveryCommunity().login(null, null, null);
	}
}