/**
 * @description Selector class for CMN_ObjectShareInstruction__e platform event
 *
 * @see CMN_ObjectShareInstruction__e
 *
 * @author vishakha.saini@accenture.com prashant.k.jain@accenture.com
 *
 * @date June 2022
 */
public inherited sharing class CMN_DAL_ObjectShareInstruction
{
	/**
	 * @description Delete Operation Name to be used when creating platform event
	 */
	public static final String OPERATION_DELETE = 'Delete';
	/**
	 * @description Insert Operation Name to be used when creating platform event
	 */
	public static final String OPERATION_INSERT = 'Insert';
	/**
	 * @description Update Operation Name to be used when creating platform event
	 */
	public static final String OPERATION_UPDATE = 'Update';
}