/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_FinServ_AccountAccountRelationTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_FinServ_AccountAccountRela00Trigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new FinServ__AccountAccountRelation__c());
    }
}