/**
 * @description Public class to use define the profile in other classes.
 *
 * @author jayanth.kumar.s@accenture.com uttpal.chandra@accenture.com
 *
 * @date 2021, March 2023
 */
public inherited sharing class SC_DAL_Profile
{
	/**
	 * @description Constant used to store the Service Agent profile name
	 */
	public static final String PROFILE_SERVICE_AGENT = 'Liberty Servicing Agent';
	/**
	 * @description Constant used to store the Retail Knowledge Administrator profile name
	 */
	public static final String PROFILE_RETAIL_KNOWLEDGE_ADMINISTRATOR = 'Liberty Retail Knowledge Administrator';
}